### PR TITLE
Coverage Report for Added and Modified Files

### PR DESCRIPTION
**Pull request by RestlessThinker**
In addition to showing overall project coverage, we wanted the ability to show the coverage on the individual files added or modified.

### CODE REVIEW

**Comment by RestlessThinker** [comment]
@marcelofabri I can't figure out why the build is failing. Tests pass locally, it looks like it can't find a gem version? Also I'd love to get your opinion on this PR. Thanks!

**Comment by marcelofabri** [comment]
@RestlessThinker I think you need to run `bundle install` to update the Gemfile.lock to use `0.3.0` since you've bumped the version number.

Could you also post a sample comment here that shows this feature as if Danger commented on this issue?

**Comment by RestlessThinker** [comment]
### Code Coverage

| File                 | Coverage |
|----------------------|----------|
| lib/simplecov_json/plugin.rb | 100.00%   |

**Review by marcelofabri — APPROVED** [review]

**Comment by marcelofabri** [comment]
This was released as 0.3.0 🎉 

Thanks!

**Pull request merged**
